language: python

python:
  - 2.7

install:
  - pip install tornado
  - pip install greenlet
  - pip install pymemcache
  - pip install PyMySQL
  - pip install storm


before_script:
  - python setup.py install

script:
  - cd tests
  - python test_travis.py&
  - pid=$!
  - kill $pid

branches:
  except:
    - legacy
